language: go

service:
  - docker

go:
   - "1.14.x"

os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "qvA7NM3cEhj8fB+dCXpIJB26WzXHr+N5c4AdwC5m4o6ncbAztd5IoZq5tMbz07CoBqgeXYIro+5M1iLr16Yisl/lVUI8qylKlwxlHyS7ddvNDcH0p50KkMdFkazgfX2ujpQJPXEA6R5fkgTs8MyUOd0opmOt1Q0xrHEKYS3jF16tw1dkiNFi3sXiv7KKVd/WHdgCQzR+9kC4xILcV/2l9saoCaXMBfQFgAWx2jC5829w0ZjLSA2wkQXZrdBGAmU+CfsbsYey+i5vRHt8zTl9zKcWnlDtOlIeI0zUdf8eCNadmrexuVo9Ak0c/ViiFWDXaq/zNwaRO1WwbZ20ZZRZlZj1fzsWRz7lNnMPaS5q9+oCjkfeZtUhtPo2bpWHPc/LVfPQIYJ47a8+eZLVE+pzKDsCO0rGqLMZ4V8nJYK9DtKzLWhSlr+mOUSvVNwe17WhKSD2rNqoFQ3VkjJ3PVVhXzY1V6eRcaXPvBrLUcc+JJkkwHi7fC3KA4++2w/Ya2WpUDzbASF/oG+jDrQHG0CSYXhKBQLDj+xIruCt5md6aEBm18t+0NPC/sOWh5s9iV0mBAMiUC/8YMTrkMdmyNePRB5YUoVjBNDrWn1czn3j9/CzciieJbn3/xHm+wyAwMGX2KaY2DY/7/uu/r+xYDeenh527BNaz/iz+3tM+qgS1Dw="
  
env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_TYPE="make"
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

before_install:
  - ./build/install-dependencies.sh
  - export IV_REPO_ROOT=$TRAVIS_BUILD_DIR

stages:
  - lint
  - build
  - test-unit
  - test-e2e
  - publish

jobs:
  include:
    - stage: lint
      name: "Run code lint"
      script:
         - |
           make lint
    - stage: build
      name: "Build the image and push it"
      script:
         - |
           make init
           make component/build
           make sec-scan
    - stage: test-unit
      name: "Run unit test"
      script:
        - set -e
        - |
          make init
          make component/test/unit
          make dependencies
          make sonar-go-test-iv
          make sonar-go-test-op
          # make sonar/go enable it after resolving package references to upstream repo
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      script:
        - |
          make init
          make component/pull
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: env(ENABLE_PUBLISH) = true AND type = push AND branch = master
      script:
        - |
          make init
          make component/build
          make publish
          #${TRAVIS_BUILD_DIR}/build/pipeline.sh
